/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MineroControler;

/**
 *
 * @author Isaac
 */
public class Clasificaciones extends javax.swing.JFrame {

    /**
     * Creates new form Predicciones
     */
    public Clasificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPanelResul = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        buttonPredecir = new javax.swing.JButton();
        comboBoxPredicciones = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SAES DM - Clasificación");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("SAES DM - Clasificación");

        jScrollPane1.setViewportView(textPanelResul);

        buttonPredecir.setText("Predecir");
        buttonPredecir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPredecirActionPerformed(evt);
            }
        });

        comboBoxPredicciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KMeans: Calif ->  Por edad y Genero", "RandomTree: Calif -> Edad, Genero", " " }));
        comboBoxPredicciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPrediccionesActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\img\\nws.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(comboBoxPredicciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonPredecir, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPredecir)
                    .addComponent(comboBoxPredicciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxPrediccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPrediccionesActionPerformed
         int seleccion = comboBoxPredicciones.getSelectedIndex();
        switch(seleccion){
            case 0:
                   textPanelResul.setText("Clasificar alumnos de acuerdo a su \nedad y la calificación que da a su profesor");
                break;
            case 1:
                    textPanelResul.setText("Clasificar alumnos de acuerdo a: \n>EDAD \n>PLANTEL\n>MATERIA");
                break;
        }
    }//GEN-LAST:event_comboBoxPrediccionesActionPerformed

    private void buttonPredecirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPredecirActionPerformed
        MineroControler minero = new MineroControler();
        int seleccion = comboBoxPredicciones.getSelectedIndex();
        System.out.println("Seleccion: " + comboBoxPredicciones.getSelectedItem());
        switch(seleccion){
            case 0:
                    minero.setARFF("C:\\arff\\ALUMNO_GEN_ED_CAL.arff" , "");  //C:\\Users\\Isaac\\Desktop\\ProyectoMineria\\ALUMNO_GEN_ED_CAL.arff
                    textPanelResul.setText(minero.clasificarSimpleKmeans());
            break;
            
            case 1:
                    minero.setARFF("C:\\arff\\ALUMNO_GEN_ED_CAL.arff", "");
                    textPanelResul.setText( minero.clasificardorArbolAleat("genero") );
            break;
                
        }
        
    }//GEN-LAST:event_buttonPredecirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clasificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPredecir;
    private javax.swing.JComboBox comboBoxPredicciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane textPanelResul;
    // End of variables declaration//GEN-END:variables
}
