/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MineroControler;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac
 */
public class Predicciones extends javax.swing.JFrame {

    /**
     * Creates new form Predicciones
     */
    public Predicciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboBoxPredicciones = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelResul = new javax.swing.JTextPane();
        buttonPredecir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("SAES DM - Predicción");

        comboBoxPredicciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Modelo: Calificación -> Edad, EvalProfesor, EvalMateria", "Modelo: Calificación -> Edad, Universidad, Materia, EvalMateria", " " }));
        comboBoxPredicciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPrediccionesActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(panelResul);

        buttonPredecir.setText("Predecir");
        buttonPredecir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPredecirActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\img\\nws.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxPredicciones, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPredecir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPredicciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPredecir))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxPrediccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPrediccionesActionPerformed
        
        int seleccion = comboBoxPredicciones.getSelectedIndex();
        switch(seleccion){
            case 0:
                   panelResul.setText("Predecir la calificación de un alumno de acuerdo a su \nedad y la calificación que da a su profesor");
                break;
            case 1:
                    panelResul.setText("Predecir la calificación de un alumno de acuerdo a: \n>EDAD \n>PLANTEL\n>MATERIA");
                break;
        }
        
    }//GEN-LAST:event_comboBoxPrediccionesActionPerformed

    private void buttonPredecirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPredecirActionPerformed
        MineroControler minero = new MineroControler();
        int seleccion = comboBoxPredicciones.getSelectedIndex();
        switch(seleccion){
            case 0:
                String nuevoReg = JOptionPane.showInputDialog(this, "Introduzca los datos a evaluar. \nEn formato: edad,evaluacionProfesor \nPara obtener calificacionMateria");
                String nregP[] = nuevoReg.split(",");
                minero.setARFF("C:\\arff\\ALUMNO_CALIFS.arff" , nuevoReg);
                String resultado = minero.regresionLineal();
                String complemento = "\n\n\n\n*** EVALUACION ***\n\nUn alumno de " + nregP[0] + " años que evalúa a su profesor con " + nregP[1] + " \npuede obtener un " + minero.getValorCalculado() +" como calificación";    
                panelResul.setText(resultado + complemento);
                break;
            
            case 1:
                String nuevoReg1 = JOptionPane.showInputDialog(this, "Introduzca los datos a evaluar. \nEn formato: EDAD,PLANTEL,MATERIA\nPara obtener calificacionMateria");
                String nregP1[] = nuevoReg1.split(",");
                minero.setARFF("C:\\arff\\ALUMN_EDAD_PLANT_MAT_EVAL.arff" , nuevoReg1);
                String resultado1 = minero.regresionLineal();
                String complemento1 = "\n\n\n\n*** EVALUACION ***\n\nUn alumno de " + nregP1[0] + " años que cursa " + nregP1[2] + " en " + nregP1[1] + "\npuede obtener un " + minero.getValorCalculado() +" como calificación";    
                panelResul.setText(resultado1 + complemento1);
                break;
        }
    }//GEN-LAST:event_buttonPredecirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Predicciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPredecir;
    private javax.swing.JComboBox comboBoxPredicciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane panelResul;
    // End of variables declaration//GEN-END:variables
}
